const fs   = require("fs");
const path = require("path");

const CONTRACT_TO_ENV = {
  PropertyTokenFactory:        "NEXT_PUBLIC_PROPERTY_TOKEN_FACTORY",
  SecurityTokenFactory:        "NEXT_PUBLIC_SECURITY_TOKEN_FACTORY",
  PropertyNFTFactory:          "NEXT_PUBLIC_PROPERTY_NFT_FACTORY",
  CREFactory:                  "NEXT_PUBLIC_CRE_FACTORY",
  PropertyLLCFactory:          "NEXT_PUBLIC_PROPERTY_LLC_FACTORY",
  InvestorRegistryFactory:     "NEXT_PUBLIC_INVESTOR_REGISTRY_FACTORY",
  GovernanceFactory:           "NEXT_PUBLIC_GOVERNANCE_FACTORY",
  DistributionManagerFactory:  "NEXT_PUBLIC_DISTRIBUTION_MANAGER_FACTORY",
};

// broadcast dir is ../contracts/broadcast relative to this script (scripts/ → app root → contracts/)
const broadcastDir = path.resolve(__dirname, "../../contracts/broadcast");
// .env.local lives at the frontend root (one level up from scripts/)
const envLocalPath = path.resolve(__dirname, "../.env.local");

function walk(dir, result) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, result);
    } else if (entry.name === "run-latest.json") {
      try {
        const data = JSON.parse(fs.readFileSync(full, "utf-8"));
        for (const tx of data.transactions ?? []) {
          if (tx.transactionType !== "CREATE") continue;
          const envKey = CONTRACT_TO_ENV[tx.contractName];
          if (envKey && tx.contractAddress) {
            result[envKey] = tx.contractAddress;
          }
        }
      } catch {}
    }
  }
}

if (!fs.existsSync(broadcastDir)) {
  console.log("[broadcast-env] contracts/broadcast/ not found — skipping");
  process.exit(0);
}

const broadcast = {};
walk(broadcastDir, broadcast);

if (Object.keys(broadcast).length === 0) {
  console.log("[broadcast-env] no factory addresses found in broadcast files");
  process.exit(0);
}

// Read existing .env.local so we don't clobber user-set values
const existing = {};
if (fs.existsSync(envLocalPath)) {
  for (const line of fs.readFileSync(envLocalPath, "utf-8").split("\n")) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) existing[match[1].trim()] = match[2].trim();
  }
}

// Merge: existing wins, broadcast fills gaps
const merged = { ...broadcast, ...existing };

// Write back
const lines = Object.entries(merged).map(([k, v]) => `${k}=${v}`);
// Preserve any non-factory lines from existing .env.local
const existing_non_factory = Object.entries(existing)
  .filter(([k]) => !Object.values(CONTRACT_TO_ENV).includes(k))
  .map(([k, v]) => `${k}=${v}`);

const all_factory = Object.values(CONTRACT_TO_ENV);
const factory_lines = all_factory
  .filter(k => merged[k])
  .map(k => `${k}=${merged[k]}`);

const final_lines = [
  "# Auto-generated by scripts/broadcast-env.js — factory addresses from forge broadcast",
  "# Manually set values here override the broadcast values.",
  ...factory_lines,
  "",
  ...existing_non_factory,
].filter((l, i, a) => l !== "" || a[i - 1] !== "");  // dedupe blank lines

fs.writeFileSync(envLocalPath, final_lines.join("\n") + "\n");

console.log("[broadcast-env] wrote factory addresses to .env.local:");
for (const k of all_factory) {
  if (merged[k]) console.log(`  ${k}=${merged[k]}`);
}
