/**
 * generate-abis.js
 * Fully dynamic — walks contracts/src/**\/*.sol, derives export names, reads
 * every ABI from contracts/out/. No hardcoded contract list.
 *
 * Run: node scripts/generate-abis.js
 * Wired into prebuild/predev in package.json.
 */

const fs   = require("fs");
const path = require("path");

// ── Path resolution ────────────────────────────────────────────────────────────
// Works in two layouts:
//   Local dev:  <repo>/frontend/scripts/ → ../../contracts/
//   Docker:     /app/scripts/            → ../contracts/  (frontend copied flat into /app)
function findContractsDir() {
  const candidates = [
    path.resolve(__dirname, "../../contracts"),  // local dev
    path.resolve(__dirname, "../contracts"),     // Docker flat
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return candidates[0];
}

const contractsDir = findContractsDir();
const srcDir       = path.join(contractsDir, "src");
const outDir       = path.join(contractsDir, "out");
const outputFile   = path.resolve(__dirname, "../lib/contracts/abis.ts");

// ── Helpers ────────────────────────────────────────────────────────────────────

// Recursively collect all .sol files under a directory
function walkSol(dir, result = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walkSol(full, result);
    else if (entry.name.endsWith(".sol")) result.push(full);
  }
  return result;
}

// PascalCase contract name → SCREAMING_SNAKE_ABI
// e.g. "PropertyNFTFactory" → "PROPERTY_NFT_FACTORY_ABI"
function toExportName(contractName) {
  // Insert underscore before each uppercase run that follows a lowercase letter
  // or before an uppercase letter followed by a lowercase letter (handles acronyms)
  const snake = contractName
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toUpperCase();
  return `${snake}_ABI`;
}

// Strip internalType — not needed by viem
function stripInternal(abi) {
  return JSON.parse(JSON.stringify(abi, (key, val) =>
    key === "internalType" ? undefined : val
  ));
}

function loadAbi(contractName) {
  const jsonPath = path.join(outDir, `${contractName}.sol`, `${contractName}.json`);
  if (!fs.existsSync(jsonPath)) {
    console.warn(`[generate-abis] WARNING: artifact not found: ${jsonPath}`);
    return null;
  }
  return JSON.parse(fs.readFileSync(jsonPath, "utf-8")).abi;
}

// ── Discover all contracts in src/ ────────────────────────────────────────────

if (!fs.existsSync(srcDir)) {
  console.error(`[generate-abis] ERROR: contracts/src not found at ${srcDir}`);
  process.exit(1);
}

const solFiles     = walkSol(srcDir);
const contractNames = solFiles.map(f => path.basename(f, ".sol"));

// Also include ERC20 from OZ (used as USDC interface in the frontend)
const extraContracts = ["ERC20"];

const allContracts = [...new Set([...contractNames, ...extraContracts])];

// ── Generate ───────────────────────────────────────────────────────────────────

const lines = [];

lines.push(`/**`);
lines.push(` * AUTO-GENERATED by scripts/generate-abis.js`);
lines.push(` * Source: contracts/src/ + contracts/out/ (forge build artifacts)`);
lines.push(` * DO NOT edit by hand — changes will be overwritten on next build.`);
lines.push(` */`);
lines.push(``);

// Hand-maintained TS type (not derivable from ABI)
lines.push(`export type CRESystem = {`);
lines.push(`  securityToken:       \`0x\${string}\`;`);
lines.push(`  distributionManager: \`0x\${string}\`;`);
lines.push(`};`);
lines.push(``);

const emitted = [];

for (const contractName of allContracts) {
  const abi = loadAbi(contractName);
  if (!abi) continue;

  const exportName = toExportName(contractName);
  const clean      = stripInternal(abi);

  lines.push(`// ── ${contractName} ${"─".repeat(Math.max(0, 74 - contractName.length))}`);
  lines.push(``);
  lines.push(`export const ${exportName} = ${JSON.stringify(clean, null, 2)} as const;`);
  lines.push(``);

  emitted.push(exportName);
}

// ── Address exports (from env vars written by broadcast-env.js) ───────────────

const ADDRESS_EXPORTS = [
  ["PROPERTY_TOKEN_FACTORY_ADDRESS", "NEXT_PUBLIC_PROPERTY_TOKEN_FACTORY"],
  ["CRE_FACTORY_ADDRESS",            "NEXT_PUBLIC_CRE_FACTORY"],
  ["SECURITY_TOKEN_FACTORY_ADDRESS", "NEXT_PUBLIC_SECURITY_TOKEN_FACTORY"],
  ["PROPERTY_NFT_FACTORY_ADDRESS",   "NEXT_PUBLIC_PROPERTY_NFT_FACTORY"],
  ["PROPERTY_LLC_FACTORY_ADDRESS",   "NEXT_PUBLIC_PROPERTY_LLC_FACTORY"],
  ["INVESTOR_REGISTRY_FACTORY_ADDRESS", "NEXT_PUBLIC_INVESTOR_REGISTRY_FACTORY"],
  ["GOVERNANCE_FACTORY_ADDRESS",     "NEXT_PUBLIC_GOVERNANCE_FACTORY"],
  ["DISTRIBUTION_MANAGER_FACTORY_ADDRESS", "NEXT_PUBLIC_DISTRIBUTION_MANAGER_FACTORY"],
];

lines.push(`// ── Contract addresses (from env) ─────────────────────────────────────────────`);
lines.push(``);
for (const [exportConst, envVar] of ADDRESS_EXPORTS) {
  lines.push(`export const ${exportConst} =`);
  lines.push(`  (process.env.${envVar} as \`0x\${string}\` | undefined) ?? undefined;`);
  lines.push(``);
}

fs.writeFileSync(outputFile, lines.join("\n"), "utf-8");
console.log(`[generate-abis] wrote ${outputFile} (${emitted.length} ABIs: ${emitted.join(", ")})`);
